[project]
name = "uc-intg-tapo"
version = "0.3"
description = "TP-Link Tapo integration for Unfolded Circle Remote 2/3"
readme = "README.md"
license = { text = "MPL-2.0" }
authors = [
    { name = "Ashley Finney" }
]
requires-python = ">=3.11"
dependencies = [
    "ucapi>=0.5.3",
    "ucapi-framework>=1.9.1",
    "python-kasa>=0.10.2",
    "aiohttp>=3.9.0",
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["uc_intg_tapo"]
